# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Team.create({"name"=>"Rusia"})
Team.create({"name"=>"Arabia Saudita"})
Team.create({"name"=>"Egipto"})
Team.create({"name"=>"Uruguay"})
Team.create({"name"=>"Espana"})
Team.create({"name"=>"Iran"})
Team.create({"name"=>"Marruecos"})
Team.create({"name"=>"Portugal"})
Team.create({"name"=>"Australia"})
Team.create({"name"=>"Dinamarca"})
Team.create({"name"=>"Francia"})
Team.create({"name"=>"Peru"})
Team.create({"name"=>"Argentina"})
Team.create({"name"=>"Croacia"})
Team.create({"name"=>"Islandia"})
Team.create({"name"=>"Nigeria"})
Team.create({"name"=>"Brasil"})
Team.create({"name"=>"Costa Rica"})
Team.create({"name"=>"Serbia"})
Team.create({"name"=>"Suiza"})
Team.create({"name"=>"Alemania"})
Team.create({"name"=>"Corea del Sur"})
Team.create({"name"=>"Mexico"})
Team.create({"name"=>"Suecia"})
Team.create({"name"=>"Belgica"})
Team.create({"name"=>"Inglaterra"})
Team.create({"name"=>"Panama"})
Team.create({"name"=>"Tunez"})
Team.create({"name"=>"Colombia"})
Team.create({"name"=>"Japon"})
Team.create({"name"=>"Polonia"})
Team.create({"name"=>"Senegal"})